# Environmental Data Collection

**About:**

This section of the repository contains information and code detailing the gathering of environmental data to describe historical conditions as well as future projected conditions from an ensemble of CMIP6 global climate models. The code for this stage is found here as well as in a [seperate repository focused on sea surface temperature](github.com/adamkemberling/oisst_mainstays).

## Steps
This stage of the workflow includes three steps. The first step is collecting data for historical conditions, which includes data from the National Geographic Data Center's ETOPO1 Global Relief Model (Amante and Eakins 2009, NOAA NGDC 2009), the NOAA Optimum Interpolated Sea Surface Temperature v2 product (Huang et al. 2020) and the University of Maryland Simple Ocean Data Assimilation product (SODA; Carton et al. 2000, Carton and Griese 2008, Carton et al. 2018). The second step captures downloading and processing global climate model CMIP6 projections for the SSP5 8.5 scenario (**add ref**). Finally, the third steps bias corrects the global climate model projections using climatologies derived from the historical environmental conditions datasets.

1. Collecting and processing historical environmental conditions data. 

    1a. Bathymetry data. We dowloaded bathymetry data from NOAA's ETOPO1 gobal relief model [online](https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/cell_registered/georeferenced_tiff/).

    1b. Sea surface temperature. Sea surface temperature from OISSTv2 Data was downloaded as annual NetCDF files from the [Physical Science Laboratory](https://psl.noaa.gov/data/gridded/data.noaa.oisst.v2.highres.html). After downloading the data, we then used functions located in a separate repository dedicated to the pre-processing of different OISST products exists and can be found [here](github.com/adamkemberling/oisst_mainstays). This repo covers the acquisition of OISST daily data from NCEI through the creation of daily climatologies and anomaly timeseries. From these daily datasets we then derived monthly averages to match the time-steps of CMIP6 and SODA data.

    1c. Bottom temperature, sea surface salinity and bottom salinity. We used the SODA product for these other environmental variables. We downloaded annual, monthly NetCDF files from the [University of Maryland](https://www2.atmos.umd.edu/~ocean/index_files/soda3.4.2_mn_download_b.htm) server using their linux wget commands. 

2. Dowloading and processing global climate model CMIP6 projected environmental conditions data. The process and associated code for downloading and processing projected environmental conditions data is in the [CMIP6_processing folder](**add link**), which includes an associated [README file](**add link**).

3. Calculating reference climatologies and bias correcting CMIP6 projected data. The process and associated code for downloading and processing projected environmental conditions data is in the [CMIP6_processing folder](**add link**), which includes an associated [README file](**add link**). 


## Next stages

The products from these three steps include a raster layer of bottom depth, raster stacks for each of the historical environmental covariates (sea surface temperature, bottom temperature, sea surface salinity, bottom salinity), and then raster stacks for the bias corrected CMIP6 ensemble 5th percentile, mean, and 95th percentile of each of the environmental covariates. The depth and historical environmental covariate rasters are transfered into the TargetsSDM workflow repo within the `data/covariates/static` and `data/covariates/dynamic` folders **add link**, while the bias corrected CMIP6 ensemble rasters are transferred to the `data/predict/raw` folders within the TargetsSDM workflow repo. Ultimately, these rasters are then used during the species distribution model fitting and projection stage to enhance the tow data as potential covariates to use in the distribution models.  

## References

Amante, C; Eakins, B W (2009): ETOPO1 Global Relief Model converted to PanMap layer format. NOAA-National Geophysical Data Center, PANGAEA, https://doi.org/10.1594/PANGAEA.769615
Carton, J.A., G. Chepurin, X. Cao, B. Giese, 2000: A Simple Ocean Data Assimilation Analysis of the Global Upper Ocean 1950–95. Part I: Methodology. J. Phys. Oceanogr. 30, 294–309.

Carton, J.A. and B. Giese, 2008: A Reanalysis of Ocean Climate Using Simple Ocean Data Assimilation (SODA. Mon. Weath. Rev. 136, 2999-3017.

Carton, J.A., G.A. Chepurin, and L. Chen, 2018: SODA3: a new ocean climate reanalysis, J. Clim. 31, 6967-6983, DOI:10.1175/JCLI-D-18-0149.1.

Huang, B., C. Liu, V. Banzon, E. Freeman, G. Graham, B. Hankins, T. Smith, and H.-M. Zhang, 2020: Improvements of the Daily Optimum Interpolation Sea Surface Temperature (DOISST) Version 2.1, Journal of Climate, 34, 2923-2939. doi: 10.1175/JCLI-D-20-0166.1

NOAA National Geophysical Data Center. 2009: ETOPO1 1 Arc-Minute Global Relief Model. NOAA National Centers for Environmental Information. Accessed [date].
Also cite the NOAA Technical Memorandum: Amante, C. and B.W. Eakins, 2009. ETOPO1 1 Arc-Minute Global Relief Model: Procedures, Data Sources and Analysis. NOAA Technical Memorandum NESDIS NGDC-24. National Geophysical Data Center, NOAA. doi:10.7289/V5C8276M [access date].



