# Environmental Data Collection

**About:**

This section of the repository contains information and code detailing the gathering of environmental data to describe historical conditions as well as future projected conditions from an ensemble of CMIP6 global climate models. The code for this stage is found in a [seperate repository focused on sea surface temperature](https://github.com/adamkemberling/oisst_mainstays) as well as within this repository and the CMIP6_Processing folder. 

## Steps
This stage of the workflow includes three steps. The first step collects data for historical conditions, which includes data from the National Geographic Data Center's ETOPO1 Global Relief Model (Amante and Eakins 2009, NOAA NGDC 2009), the NOAA Optimum Interpolated Sea Surface Temperature v2 product (Huang et al. 2020) and the University of Maryland Simple Ocean Data Assimilation product (SODA; Carton et al. 2000, Carton and Griese 2008, Carton et al. 2018). The second step captures downloading and processing global climate model [CMIP6 projections for the SSP5 8.5 scenario](Riahi et al. 2017). Finally, the third steps bias corrects the global climate model projections using climatologies derived from the historical environmental conditions data sets.

1. Collecting and processing historical environmental conditions data. 

    1a. Bathymetry data. We dowloaded bathymetry data from NOAA's ETOPO1 gobal relief model [online](https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/cell_registered/georeferenced_tiff/).

    1b. Sea surface temperature. Sea surface temperature from OISSTv2 Data was downloaded as annual NetCDF files from the [Physical Science Laboratory](https://psl.noaa.gov/data/gridded/data.noaa.oisst.v2.highres.html). After downloading the data, we then used functions located in a separate repository dedicated to the pre-processing of different OISST products exists and can be found [here](https://github.com/adamkemberling/oisst_mainstays). This repository covers the acquisition of OISST daily data from NCEI through the creation of daily climatologies and anomaly timeseries. From these daily datasets we then derived monthly averages to match the time-steps of CMIP6 and SODA data.

    1c. Bottom temperature, sea surface salinity and bottom salinity. We used the SODA product for these other environmental variables. We downloaded annual, monthly NetCDF files from the [University of Maryland](https://www2.atmos.umd.edu/~ocean/index_files/soda3.4.2_mn_download_b.htm) server using their linux wget commands. 

2. Downloading and processing global climate model CMIP6 projected environmental conditions data. The process and associated code for downloading and processing projected environmental conditions data is in the [CMIP6_processing folder](https://github.com/gulfofmaine/sdm_workflow/tree/main/CMIP6_processing), which includes an associated [README file](https://github.com/gulfofmaine/sdm_workflow/blob/main/CMIP6_processing/README.md) to guide interested folks through our approach.

3. Calculating reference climatologies and bias correcting CMIP6 projected data. The process and associated code for downloading and processing projected environmental conditions data is also in the [CMIP6_processing folder](https://github.com/gulfofmaine/sdm_workflow/tree/main/CMIP6_processing).

## Output

The products from these three steps include a raster layer of bottom depth, raster stacks for each of the historical environmental covariates (sea surface temperature, bottom temperature, sea surface salinity, bottom salinity), and then raster stacks for the bias corrected CMIP6 ensemble 5th percentile, mean, and 95th percentile of each of the environmental covariates.

## Next stages

 The depth and historical environmental covariate rasters are transferred into the TargetsSDM workflow repository within the `data/covariates/static` and `data/covariates/dynamic` folders, while the bias corrected CMIP6 ensemble rasters are transferred to the `data/predict/raw` folders within the TargetsSDM workflow repository. Ultimately, these rasters are then used to [enhance the tow data][Enhancing Biological Data With Environmental Data] by extracting environmental variables at each unique tow location to use as potential covariates in the species distribution models.






